### ISSUE TITLE
How *not* to make a swap partition?

### ISSUE THREAD

**Issue by Gullumluvl** [rdkr/ubuntu-lvm-on-luks#3]
Hello,

I actually have a usage question : my drive is a SSD, and I don't want to set up a swap partition. Will this work as intended if I set swap size to 0 ?

**Comment by rdkr** [comment]
Hey, if you comment out this line before running the script it should prevent swap being created at all:

https://github.com/rdkr/lvm-on-luks/blob/master/lvm-on-luks#L26

Happy to accept PRs to improve the script!

**Comment by Gullumluvl** [comment]
Thanks for the hint!
I tried myself the manual steps (without this project) but it's still quite obscure to me (still can't boot).
Can I use this script to install with uefi (+encrypted boot setup)? (I should maybe open a separate issue about this, because I have started to collect information about extra steps that seem required, but again, I haven't managed yet).

**Comment by rdkr** [comment]
There's nothing I'm aware of that should prevent this working with UEFI, but I've not tried it. Feel free to open a new issue if you've gathered any more info - I'll close this one for now.
